# Generated by Django 5.2.12 on 2026-03-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_acessorio_cor_modelo_veiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorio',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorio',
            field=models.ManyToManyField(related_name='veiculos', to='core.acessorio'),
        ),
    ]
